/*
-- Query: SELECT * FROM servercis.lhr_medication
LIMIT 0, 1000

-- Date: 2015-09-28 17:25
*/
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10003','Klinik UTeM Induk','2015-04-09','MCA006002','Cloxacillin  cap',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'891031075331','M031210005','normal','FTMK');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10008','Klinik UTeM Induk','2015-04-09','MIN003002','Ventolin inhaler',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'888888888','10003','normal','FKE');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10010','Klinik UTeM Induk','2015-04-09','MCA006002','Cloxacillin  cap',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'870409045212','M031110010','normal','FTMK');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10015','Klinik UTeM Induk','2015-04-09','MCA006002','Cloxacillin  cap',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'891031065213','M031210009','normal','FTMK');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10021','Hospital Melaka','2015-04-09','MLA018003','Betnovate + Neomycin cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'555555063333','10027','normal','FKEKK');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10022','Klinik UTeM Induk','2015-04-09','MLA018003','Betnovate + Neomycin cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'660207015261','10098','normal','FTMK');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10023','Hospital Melaka','2015-04-09','MIN003002','Ventolin inhaler',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'891031065777','M031210002','normal','FKP');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10024','Hospital Melaka','2015-04-09','MCA006002','Cloxacillin  cap',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'890906145163','M031210004','normal','FKM');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10025','Hospital Melaka','2015-04-09','MCA006002','Cloxacillin  cap',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'910906145167','M031310005','normal','FTMK');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10026','Klinik UTeM Induk','2015-04-09','MLA018003','Betnovate + Neomycin cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'660206015261','10052','normal','FTK');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10027','Klinik UTeM Induk','2015-04-09','MLA018019','Vaseline ointment',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'890723115555','M031210017','normal','FTMK');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10028','Klinik UTeM Induk','2015-04-09','MIN003002','Ventolin inhaler',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'890505145050','M031210022','normal','FTMK');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10029','Hospital Melaka','2015-04-09','MLA018003','Betnovate + Neomycin cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'820626125395','M031010010','normal','FPTT');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10030','Klinik UTeM Induk','2015-04-09','MLA018003','Betnovate + Neomycin cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'890723115552','M031210013','normal','FKE');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10031','Klinik UTeM Induk','2015-04-09','MLA018019','Vaseline ointment',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'760113055043','10055','normal','FKP');
INSERT INTO `lhr_medication` (`PMI_no`,`hfc_code`,`Episode_date`,`Medication_code`,`Medication_desc`,`Requested_drug_from_code`,`Requested_drug_from_desc`,`Requested_drug_route_code_066`,`Detail_reference_code`,`Description`,`Requested_drug_frequency_code`,`Requested_drug_frequency_from_desc`,`Requested_drug_frequency_unit`,`Requested_dosage`,`Requested_drug_strength`,`Requested_quantity`,`start_date`,`end_date`,`NATIONAL_ID_NO`,`PERSON_ID_NO`,`PERSON_STATUS`,`LOCATION_CODE`) VALUES ('PMS10032','Klinik UTeM Induk','2015-04-09','MIN003002','Ventolin inhaler',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'891031145213','M031210006','normal','FKE');
