/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import static java.nio.file.Files.list;
import static java.rmi.Naming.list;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.RMIConnector;
import static org.eclipse.persistence.jpa.jpql.utility.CollectionTools.list;

/**
 *
 * @author adam
 */
public class Report1 extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Connection conn1 = null;
    ResultSet rs1 = null;
    PreparedStatement pst1 = null;
    String Sub, Sub2 = null;

    //Declare PDF Report function
    private BaseFont bfBold;
    private BaseFont bf;
    private int pageNumber = 0;

    /**
     * Creates new form Report1
     */
    public Report1() {
        initComponents();
//        fillcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Report Type: ");

        jLabel3.setText("By:");

        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Report and statistic of pharmacy");

        jLabel7.setText("Of:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Please Select-", "Total & Drug Type", "Total Drug Expenses", "Stock Take & Stock Count" }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setText("Facuty:");

        jComboBox5.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox5PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7))
                            .addComponent(jLabel9))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String jcombox = (String) jComboBox1.getSelectedItem();
//        //ArrayList<String> list = new ArrayList<String>();
        Sub = jcombox;

        if ("Total & Drug Type".equals(Sub)) {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("ALL");
            jComboBox2.addItem("That has been used");
            jComboBox2.addItem("That has been expired");
            jComboBox3.removeAllItems();
            jComboBox3.addItem("Weeks");
            jComboBox3.addItem("Months");
            jComboBox3.addItem("Years");
            week();
            fillcombo();

        } else if ("Total Drug Expenses".equals(Sub)) {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("All");
            jComboBox2.addItem("Student");
            jComboBox2.addItem("International Student");
            jComboBox2.addItem("Staff");
            jComboBox3.removeAllItems();
            jComboBox3.addItem("Months");
            jComboBox3.addItem("Years");
            month();
            fillcombo();

        } else if ("Stock Take & Stock Count".equals(Sub)) {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Total Drug in Storage & Drug Usage");
            jComboBox2.addItem("Batch Number");
            jComboBox2.addItem("Drug Type");
            jComboBox3.removeAllItems();
            jComboBox3.addItem("Months");
            jComboBox3.addItem("Years");
            month();
            fillcombo();

        } else {
            jComboBox2.removeAllItems();
            jComboBox3.removeAllItems();
            jComboBox4.removeAllItems();
            jComboBox5.removeAllItems();

        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jComboBox3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String tmp2 = (String) jComboBox3.getSelectedItem();
        Sub2 = tmp2;

        if ("Weeks".equals(Sub2)) {
            week();

        } else if ("Months".equals(Sub2)) {
            month();

        } else if ("Years".equals(Sub2)) {
            year();
        }
    }//GEN-LAST:event_jComboBox3PopupMenuWillBecomeInvisible

    private void jComboBox5PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox5PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
//        java.sql.Date sqldate = new java.sql.Date(jDateChooser1.getDate().getTime());
        String tmp = (String) jComboBox5.getSelectedItem();
        String pdfFilename = "Report1";

        try {
            generateDetailTextArea();
            generateReportPDF(pdfFilename);
        } catch (SQLException ex) {
            Logger.getLogger(Report3.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\Users\\adam\\Desktop\\Report1\\" + pdfFilename + "(" + tmp + ").pdf");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jComboBox5PopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, DocumentException, FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report1().setVisible(true);
            }
        });
    }

    private void week() {
        jComboBox4.removeAllItems();
        jComboBox4.addItem("-Please Select-");
        jComboBox4.addItem("ALL");
        jComboBox4.addItem("1");
        jComboBox4.addItem("2");
        jComboBox4.addItem("3");
        jComboBox4.addItem("4");
        jComboBox4.addItem("5");
        jComboBox4.addItem("6");
        jComboBox4.addItem("7");
    }

    private void month() {
        jComboBox4.removeAllItems();
        jComboBox4.addItem("-Please Select-");
        jComboBox4.addItem("January");
        jComboBox4.addItem("February");
        jComboBox4.addItem("March");
        jComboBox4.addItem("April");
        jComboBox4.addItem("May");
        jComboBox4.addItem("June");
        jComboBox4.addItem("July");
        jComboBox4.addItem("August");
        jComboBox4.addItem("September");
        jComboBox4.addItem("October");
        jComboBox4.addItem("November");
        jComboBox4.addItem("December");
    }

    private void year() {
        jComboBox4.removeAllItems();
        jComboBox4.addItem("-Please Select-");
        jComboBox4.addItem("ALL");
        RMIConnector rc3 = new RMIConnector();
        String host = "biocore-stag.utem.edu.my";// declaration host
        int port = 1099; //declaration port //for now, stick to this port

        String sql3 = "Select distinct(year(Episode_date)) as year from lhr_medication order by year(Episode_date) desc";
        ArrayList<ArrayList<String>> data3 = rc3.getQuerySQL(host, port, sql3);// execute query

        for (int i = 0; i < data3.size(); i++) {
            jComboBox4.addItem(data3.get(i).get(0));
        }
    }

    private void fillcombo() {
        jComboBox5.removeAllItems();
        jComboBox5.addItem("-Please Select-");
        jComboBox5.addItem("ALL");
        RMIConnector rc = new RMIConnector();
        String host = "biocore-stag.utem.edu.my";// declaration host
        int port = 1099; //declaration port //for now, stick to this port

        String sql = "Select distinct(location_code) from lhr_medication order by location_code";
        ArrayList<ArrayList<String>> data = rc.getQuerySQL(host, port, sql);// execute query

        for (int i = 0; i < data.size(); i++) {
            jComboBox5.addItem(data.get(i).get(0));
        }
    }

    ////Begin create TextArea Report///
    private void generateDetailTextArea() throws SQLException {

        jTextArea1.setText("");
        String comboB1 = (String) jComboBox1.getSelectedItem();
        String comboB2 = (String) jComboBox2.getSelectedItem();
        String comboB3 = (String) jComboBox3.getSelectedItem();
        String comboB4 = (String) jComboBox4.getSelectedItem();
        String tmp = (String) jComboBox5.getSelectedItem();
        String sql = null;
        String sql2 = null;
        String sql0 = null;
        ArrayList<ArrayList<String>> data = null;
        ArrayList<ArrayList<String>> data2 = null;

        RMIConnector rc = new RMIConnector();
        String host = "biocore-stag.utem.edu.my";// declaration host
        int port = 1099; //declaration port //for now, stick to this port
        

        if(comboB1!=null){//Report selection
            if ("Total & Drug Type".equals(comboB1)){//report 1
                if ("ALL".equals(comboB2)){//report 1.1
                    sql0 = "SELECT * FROM servercis.pis_mdc2";
                }else if ("That has been used".equals(comboB2)){//report 1.2
                    sql0 = "SELECT * FROM servercis.pis_mdc2 where D_EXP_DATE = \"\"";
                }else if ("That has been expired".equals(comboB2)){//report 1.3
                    sql0 = "SELECT * FROM servercis.pis_mdc2 where D_EXP_DATE != \"\"";
                }
                
            }else if("Total Drug Expenses".equals(comboB1)){//report 2
                if ("All".equals(comboB2) && comboB4 != null && comboB4 != "-Please Select-" && tmp != null && tmp != "-Please Select-") {//report 2.1
                    if ("ALL".equals(tmp)) {
                        sql = "select l.LOCATION_CODE, l.Medication_code, l.Medication_desc,\n"
                                + "Sum(case when PERSON_STATUS='L' then 1 else 0 end) AS Male,\n"
                                + "Sum(case when PERSON_STATUS='P' then 1 else 0 end) AS Female,\n"
                                + "COUNT(l.Medication_code) as PTotal, COUNT(LOCATION_CODE) as TTotal,\n"
                                + "COUNT(DISTINCT(l.Medication_code)) as MTotal, MONTH(Episode_date),\n"
                                + "p.D_SELL_PRICE as RM, \n"
                                + "COUNT(l.Medication_code)*p.D_SELL_PRICE as total_RM\n"
                                + "from servercis.lhr_medication AS l\n"
                                + "inner join servercis.pis_mdc2 AS p \n"
                                + "on l.Medication_code=p.UD_MDC_CODE\n"
                                + "where l.Medication_code in\n"
                                + "(\n"
                                + "select UD_MDC_CODE from pis_mdc2\n"
                                + ")\n"
                                + "group by l.Medication_code";
                        sql2 = "SELECT count(distinct(medication_code)) as TotalMed, count(medication_code) as TotalPatient FROM servercis.lhr_medication ;";

                        data = rc.getQuerySQL(host, port, sql);
                        data2 = rc.getQuerySQL(host, port, sql2);
                    } else {
                        sql = "select l.LOCATION_CODE, l.Medication_code, l.Medication_desc,\n"
                                + "Sum(case when PERSON_STATUS='L' then 1 else 0 end) AS Male,\n"
                                + "Sum(case when PERSON_STATUS='P' then 1 else 0 end) AS Female,\n"
                                + "COUNT(l.Medication_code) as PTotal, COUNT(LOCATION_CODE) as TTotal,\n"
                                + "COUNT(DISTINCT(l.Medication_code)) as MTotal, MONTH(Episode_date),\n"
                                + "p.D_SELL_PRICE as RM, \n"
                                + "COUNT(l.Medication_code)*p.D_SELL_PRICE as total_RM\n"
                                + "from servercis.lhr_medication AS l\n"
                                + "inner join servercis.pis_mdc2 AS p \n"
                                + "on l.Medication_code=p.UD_MDC_CODE\n"
                                + "where l.LOCATION_CODE = '" + tmp + "' and year(Episode_date)='" + comboB4 + "' and l.Medication_code in\n"
                                + "(\n"
                                + "select UD_MDC_CODE from pis_mdc2\n"
                                + ")\n"
                                + "group by l.Medication_code";
                        sql2 = "SELECT count(distinct(medication_code)) as TotalMed, count(medication_code) as TotalPatient FROM servercis.lhr_medication where location_code='" + tmp + "';";
                        data = rc.getQuerySQL(host, port, sql);
                        data2 = rc.getQuerySQL(host, port, sql2);
                    }
                } else if ("Student".equals(comboB2)) {//report 2.2
                    sql0 = " ";
                }else if ("International Student".equals(comboB2)){//report 2.3
                    sql0 = " ";
                }else if ("Staff".equals(comboB2)){//report 2.4
                    sql0 = " ";
                }
                
            }else if("Stock Take & Stock Count".equals(comboB1)){//report 3
                if ("Total Drug in Storage & Drug Usage".equals(comboB2)){//report 3.1
                    sql0 = " ";
                }else if ("Batch Number".equals(comboB2)){//report 3.2
                    sql0 = " ";
                }else if ("Drug Type".equals(comboB2)){//report 3.3
                    sql0 = " ";
                }
            }else{
                //null
            }
        }else{
            //null
        }

        //------------------------- header--------------------
        jTextArea1.append("\n==============");
        jTextArea1.append("\n==============");
        jTextArea1.append("\nFaculty : " + tmp);
        jTextArea1.append("\n==============");
        jTextArea1.append("\n----------------------------------------------------------------------------------");
        jTextArea1.append("\n|| CODE\t|| DESCRIPTION\t|| PRICE\t|| TOTAL PATIENT\t||TOTAL AMOUNT||");
        jTextArea1.append("\n----------------------------------------------------------------------------------");
        //------------------------- end header--------------------

        for (int j = 0; j < data.size(); j++) {

            jTextArea1.append("\n|| " + data.get(j).get(1) + "\t|| " + data.get(j).get(2) + " \t|| " + data.get(j).get(9) + "\t||" + data.get(j).get(5) + "\t||" + data.get(j).get(10) + "\t||");

            jTextArea1.append("\n----------------------------------------------------------------------------------");

        }
        jTextArea1.append("\n----------------------------------------------------------------------------------");
        jTextArea1.append("\nFaculty : " + data.get(0).get(0));
        jTextArea1.append("\nTotal Medicines : " + data2.get(0).get(0));
        jTextArea1.append("\nTotal Patients : " + data2.get(0).get(1));
        jTextArea1.append("\n----------------------------------------------------------------------------------");
        jTextArea1.append("\n----------------------------------------------------------------------------------");


    }//End TextArea Report///

    //Begin PDF report////
    private void generateReportPDF(String pdfFilename) throws SQLException {
        Document doc = new Document(PageSize.A4, 36, 36, 64, 36);
        PdfWriter docWriter = null;
        initializeFonts();

        String tmp = (String) jComboBox5.getSelectedItem();

        try {
            String path = "C:\\Users\\adam\\Desktop\\Report1\\" + pdfFilename + "(" + tmp + ").pdf";
            docWriter = PdfWriter.getInstance(doc, new FileOutputStream(path));
            doc.addAuthor("Adam");
            doc.addCreationDate();
            doc.addProducer();
            doc.addCreator("MySampleCode.com");
            doc.addTitle("Report1");
            doc.setPageSize(PageSize.LETTER);

            doc.open();
            PdfContentByte cb = docWriter.getDirectContent();

            generateDetail(doc, cb);

        } catch (DocumentException dex) {
            dex.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            if (doc != null) {
                doc.close();
            }
            if (docWriter != null) {
                docWriter.close();
            }
        }

    }

    private void generateDetail(Document doc, PdfContentByte cb) {

        String sql = null;
        RMIConnector rc = new RMIConnector();
        String host = "biocore-stag.utem.edu.my";// declaration host
        int port = 1099; //declaration port //for now, stick to this port

        String tmp = (String) jComboBox5.getSelectedItem();
        String comboB4 = (String) jComboBox4.getSelectedItem();

        if (tmp != null && tmp != "-Please Select-" && comboB4 != null && comboB4 != "-Please Select-") {
            if ("ALL".equals(tmp)) {
                sql = "select l.LOCATION_CODE, l.Medication_code, l.Medication_desc,\n"
                        + "Sum(case when PERSON_STATUS='L' then 1 else 0 end) AS Male,\n"
                        + "Sum(case when PERSON_STATUS='P' then 1 else 0 end) AS Female,\n"
                        + "COUNT(l.Medication_code) as PTotal, COUNT(LOCATION_CODE) as TTotal,\n"
                        + "COUNT(DISTINCT(l.Medication_code)) as MTotal, MONTH(Episode_date),\n"
                        + "p.D_SELL_PRICE as RM, \n"
                        + "COUNT(l.Medication_code)*p.D_SELL_PRICE as total_RM\n"
                        + "from servercis.lhr_medication AS l\n"
                        + "inner join servercis.pis_mdc2 AS p \n"
                        + "on l.Medication_code=p.UD_MDC_CODE\n"
                        + "where l.Medication_code in\n"
                        + "(\n"
                        + "select UD_MDC_CODE from pis_mdc2\n"
                        + ")\n"
                        + "group by l.Medication_code";

            } else {
                sql = "select l.LOCATION_CODE, l.Medication_code, l.Medication_desc,\n"
                        + "Sum(case when PERSON_STATUS='L' then 1 else 0 end) AS Male,\n"
                        + "Sum(case when PERSON_STATUS='P' then 1 else 0 end) AS Female,\n"
                        + "COUNT(l.Medication_code) as PTotal, COUNT(LOCATION_CODE) as TTotal,\n"
                        + "COUNT(DISTINCT(l.Medication_code)) as MTotal, MONTH(Episode_date),\n"
                        + "p.D_SELL_PRICE as RM, \n"
                        + "COUNT(l.Medication_code)*p.D_SELL_PRICE as total_RM\n"
                        + "from servercis.lhr_medication AS l\n"
                        + "inner join servercis.pis_mdc2 AS p \n"
                        + "on l.Medication_code=p.UD_MDC_CODE\n"
                        + "where l.LOCATION_CODE = '" + tmp + "' and year(Episode_date)='" + comboB4 + "' and l.Medication_code in\n"
                        + "(\n"
                        + "select UD_MDC_CODE from pis_mdc2\n"
                        + ")\n"
                        + "group by l.Medication_code";
            }

            ArrayList<ArrayList<String>> data = rc.getQuerySQL(host, port, sql);

            boolean beginPage = true;
            int y = 0;

            for (int i = 0; i < data.size(); i++) {
                if (beginPage) {
                    beginPage = false;
                    generateLayout(doc, cb);
                    generateHeader(doc, cb);
                    y = 615;
                }

                if (y < 50) {
                    printPageNumber(cb);
                    doc.newPage();
                    beginPage = true;
                }
            }
            printPageNumber(cb);

            int i = 0;
            for (int j = 0; j < data.size(); j++) {

                if (i < data.size()) {
                    DecimalFormat df = new DecimalFormat("0.00");
                    df.setMaximumFractionDigits(2);
                    createContent(cb, 63, y, String.valueOf(i + 1), PdfContentByte.ALIGN_RIGHT);
                    createContent(cb, 72, y, data.get(j).get(1), PdfContentByte.ALIGN_LEFT);
                    createContent(cb, 145, y, data.get(j).get(2), PdfContentByte.ALIGN_LEFT);

                    String RM = df.format(Double.parseDouble(data.get(j).get(9)));
                    createContent(cb, 448, y, RM, PdfContentByte.ALIGN_RIGHT);

                    createContent(cb, 518, y, data.get(j).get(5), PdfContentByte.ALIGN_RIGHT);

                    String RMTotal = df.format(Double.parseDouble(data.get(j).get(10)));
                    createContent(cb, 588, y, RMTotal, PdfContentByte.ALIGN_RIGHT);
                    y = y - 15;
                    if (y < 50) {
                        printPageNumber(cb);
                        doc.newPage();
                        beginPage = true;
                    }
                }
                i++;
            }
        }else{
            
        }
    }

    private void generateLayout(Document doc, PdfContentByte cb) {

        try {

            cb.setLineWidth(1f);

            cb.rectangle(40, 50, 550, 600);
            cb.moveTo(40, 630);//horizontal line
            cb.lineTo(590, 630);//horizontal line

            cb.moveTo(70, 50);//No
            cb.lineTo(70, 650);
            cb.moveTo(143, 50);//Drug Code
            cb.lineTo(143, 650);
            cb.moveTo(405, 50);//Desc
            cb.lineTo(405, 650);
            cb.moveTo(450, 50);//Price
            cb.lineTo(450, 650);
            cb.moveTo(520, 50);//Total Amount
            cb.lineTo(520, 650);
            cb.stroke();

            // Report Detail box Text Headings 
            createHeadings(cb, 48, 633, "No");
            createHeadings(cb, 72, 633, "Drug Code");
            createHeadings(cb, 145, 633, "Description");
            createHeadings(cb, 415, 633, "Price");
            createHeadings(cb, 457, 633, "Total Patient");
            createHeadings(cb, 522, 633, "Total Amount");

            //add the images
            Image Logo = Image.getInstance("C:\\Users\\adam\\Desktop\\LI_tuffah\\klinikal system\\gui\\Report\\LogoUTeM2.gif");
            Logo.setAbsolutePosition(45, 700);
            Logo.scalePercent(9);
            doc.add(Logo);

        } catch (DocumentException dex) {
            dex.printStackTrace();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void generateHeader(Document doc, PdfContentByte cb) {

        String tmp = (String) jComboBox5.getSelectedItem();
        String comboB4 = (String) jComboBox4.getSelectedItem();

        createHeadings(cb, 215, 762, "Pusat Kesihatan");
        createHeadings(cb, 215, 742, "Universiti Teknikal Malaysia, Melaka");
        createHeadings(cb, 215, 722, "54500 Durian Tunggal");
        createHeadings(cb, 215, 702, "Melaka");

        createHeadings(cb, 45, 684, "Report of Drug Sales by " + comboB4);
        createHeadings(cb, 45, 672, "Faculty: " + tmp);
        createHeadings(cb, 45, 660, "Report ID: ECSS RPT 002");

        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        createHeadings(cb, 465, 660, "Date: " + dateFormat.format(date));//2014/08/06 15:59:48

    }

    private void createHeadings(PdfContentByte cb, float x, float y, String text) {

        cb.beginText();
        cb.setFontAndSize(bfBold, 10);
        cb.setTextMatrix(x, y);
        cb.showText(text.trim());
        cb.endText();

    }

    private void printPageNumber(PdfContentByte cb) {

        cb.beginText();
        cb.setFontAndSize(bfBold, 9);
        cb.showTextAligned(PdfContentByte.ALIGN_RIGHT, "Page No. " + (pageNumber + 1), 570, 25, 0);
        cb.endText();

        pageNumber++;

    }

    private void createContent(PdfContentByte cb, float x, float y, String text, int align) {

        cb.beginText();
        cb.setFontAndSize(bf, 10);
        cb.showTextAligned(align, text.trim(), x, y, 0);
        cb.endText();

    }

    private void initializeFonts() {

        try {
            bfBold = BaseFont.createFont(BaseFont.HELVETICA_BOLD, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
            bf = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);

        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
    //End PDF report////


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
